[[redirects]]
  from = "/api-token/*"
  to = "https://github.com/login/oauth/access_token/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api-user"
  to = "https://api.github.com/user"
  status = 200
  force = true

[[redirects]]
  from = "/completions"
  to = "https://api.openai.com/v1/completions"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200